spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio
spring.datasource.username=root
spring.datasource.password=Hcy001105@
#spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
finnhub.api.base-url=https://finnhub.io/api/v1
finnhub.api.token=d76d6p9r01qm4b7trl20d76d6p9r01qm4b7trl2g

# Alpha Vantage candlestick data
alphavantage.api.base-url=https://www.alphavantage.co/query
alphavantage.api.key=6EBF666Y7IN7MHYG
